bboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from .views import index, other_page
from .views import BBLoginView
from .views import profile
from .views import BBLogoutView
from .views import ChangeUserInfoView
from django.contrib.auth.views import PasswordChangeView
from .views import BBPasswordChangeView, secret

app_name = 'main'
urlpatterns = [
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path ('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path ('accounts/profile/', profile, name='profile'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
    path('secret/', secret, name='secret')
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Прошел активацию?')
    send_messages = models.BooleanField(default=True, verbose_name='Слать оповещения о новых комментариях?')
    class Meta(AbstractUser.Meta):
        pass

class Secret(models.Model):
    text = models.CharField(max_length=4900)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text
    

main/forms.py
from django import forms
from .models import AdvUser

class ChangeUserInfoForm (forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from .models import AdvUser, Secret
from .forms import ChangeUserInfoForm
from django.contrib.auth.views import PasswordChangeView

class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'
    
class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
        
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'

class BBLoginView(LoginView):
    template_name = 'main/login.html'

@login_required
def profile(request):
    return render(request, 'main/profile.html')


def index(request):
    return render(request, 'main/index.html')

def secret(request):
    context = {'secret':Secret.objects}
    return render(request, 'main/secret.html', context)

def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

templates/layout/basic.html
<!DOCTYPE html>

{% load bootstrap4 %}
{% load static %}

<html>
    <head>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Главная{% endblock %} - Доска объявлений</title>
        {% bootstrap_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
        {% bootstrap_javascript jquery='slim' %}
    </head>
    <body class="container-fluid">
        <header class="mb-4">
            <h1 class="display-1 text-center">Объявления</h1>
        </header>
        <div class="row">
            <ul class="col nav justify-content-end border">
                <li class="nav-item"><a class="nav-link" href="#">Регистрация</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Профиль</a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="{% url 'main:profile' %}">Moи объявления</a>
                        <a class="dropdown-item" href="{% url 'main:profile_change'%}">Изменить личные данные</a>
                        <a class="dropdown-item" href="{% url 'main:password_change'%}">Изменить пароль</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Удалить</a>
                    </div>
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:logout' %}">Выйти</a>
                    </li>
                {% else %}
                <li class="nav-link"><a href="{% url 'main:login' %}">Вход</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="row">
            <nav class="col-md-auto nav flex-column border">
                <a class="nav-link root" href="{% url 'main:index' %}">Главная</a>
                <span class="nav-link root font-weight-bold"> Heдвижимость </span>
                <a class="nav-link" href="#">Жилье</a>
                <a class="nav-link" href="#">Склады</a>
                <a class="nav-link" href="#">Гаражи</a>
                <span class="nav-link root font-weight-bold" href="#"> Транспорт</span>
                <a class="nav-link" href="#">Легковой</a>
                <a class="nav-link" href="#">Грузовик</a>
                <a class="nav-link root" href="{% url 'main:other' page='about' %}">О сайте</a>
            </nav>
            <section class="col border py-2">
                {% bootstrap_messages %}
                {% block content %}
                {% endblock %}
            </section>
        </div>
        <footer class="mt-3">
            <p class="text-right font-italic">&copy; любой ТМ на ваш вкус</p>
        </footer>
    </body>
</html>

templates/main/about.html
{% extends "layout/basic.html" %}
{% block title %}O сайте{% endblock %}
{% block content %}
    <h2>О сайте</h2>
    <p>Сайт для публикации объявлений о продаже, разбитых на рубрики.</р>
{% endblock %}

templates/main/change_user_info.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %}Правка личных данных{% endblock %}
{% block content %}
    <h2>Правка личных данных пользователя {{ user.username }}</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Сохранить' %}{% endbuttons %}
    </form>
{% endblock %}

templates/main/index.html
{% extends "layout/basic.html" %}

{% block content %}
    <h2>Последние 10 объявлений</h2>
{% endblock %}

templates/main/login.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %}Вход{% endblock %}
{% block content %}
    <h2>Вход</h2>
    {% if user.is_authenticated %}
        <p>Вы уже выполнили вход.</р>
    {% else %}
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form layout='horizontal' %}
            <input type="hidden" name="next" value="{{ next }}">
            {% buttons submit='Войти' %}{% endbuttons %}
        </form>
    {% endif %}
{% endblock %}

templates/main/logout.html
{% extends "layout/basic.html" %}
{% block title %}Выход{% endblock %}
{% block content %}
    <h2>Выход</h2>
    <p>Вы успешно вышли с сайта.</p>
{% endblock %}

templates/main/password_change.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %}Смена пароля{% endblock %}
{% block content %}
    <h2>Смена пароля пользователя {{ user.username }}</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Сменить пароль' %}{% endbuttons %}
    </form>
{% endblock %}

templates/main/profile.html
{% extends "layout/basic.html" %}
{% block title %}Профиль пользователя{% endblock %}
{% block content %}
    <h2>Профиль пользователя {{ user.username }}</h2>
    {% if user.first_name and user.last_name %}
        <p>3дравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
    {% else %}
        <p>3дравствуйте!</p>
    {% endif %}
    <h3>Ваши объявления</h3>
{% endblock %}

templates/main/secret.html
{% for topic in secret %}
    <li>
        <p>{{topic}}</p>
    </li>
{% endfor %}